### PR TITLE
First shot at Telemetry endpoint

### PR DESCRIPTION
**Pull request by sophokles73**
I have created a first implementation of the Telemetry upload functionality based on vert.x and Proton.
So far it just checks whether message format and forwards messages via the vert.x event bus to another verticle that publishes the messages to a RabbitMQ broker.

Assuming we want to stick with the *hybrid connection model* sketched out during our face-to-face we will need to change that verticle to publish to an AMQP 1.0 node instead (e.g. a Qpid Dispatch Router or AMQP 1.0 based broker).
 
Once the vertx-proton project provides artifacts via Maven Central we should remove the vertx-proton code again ...

### CODE REVIEW

**Comment by dguggemos** [comment]
Looks good to me  :+1:

**Comment by sophokles73** [comment]
Merged to master in c6290c2

**Comment by hekonsek** [comment]
I've just reviewed the code and I like what I see :) .

**Comment by ppatierno** [comment]
Hi Kai,
the implementation looks very good ! :-)

I have just a couple of observations and one thing I can't explain to myself but I think you can help me to understand.

First of all I see a couple of parts where sending "disposition" performative to the AMQP client is useless in the case of snd-settle-mode with settled value (AT MOST ONCE).
For example in the handleTelemetryUpload() method (HonoServer class), if the TelemetryMessageFilter.verify(tenantId, message) fails we need to send disposition with REJECTED delivery status only if snd-settle-mode is not settled (AT LEAST ONCE).
The same in the sendTelemetryData() where inside sendAtMostOnce() you send disposition with ACCEPTED delivery status.

The good thing is that even if with this code, the disposition frames aren't sent by the Qpid Proton engine on which Vert.X Proton is based, because the disposition() method first verifies if the delivery is remote settled : it sends disposition only if it's not remote settled (so in the case of AT MOST ONCE, it doesn't send nothing).

By the way, I tried to remove the ProtonHelper.accepted(delivery, true); inside the sendAtMostOnce() but the HostServerTest fails. I can't find any relation between this behavior and removing the above accepted method.

Can you help me on this ?

**Comment by ppatierno** [comment]
It seems to be related on the flow control and the 20 credit you give to the client.

**Comment by sophokles73** [comment]
Hi Paolo,

you are absolutely right with your observations and the reason why I didn't make the distinction for rejecting only if the delivery mode is not AT_MOST_ONCE is exactly Proton's behavior in this regard.

Coming to your question: 
we are currently including a copy of vertx-proton in our code base because we had no released version available from Maven Central yet. The version we included is several weeks old and does not contain the changes made by Robbie regarding flow control. In the old (included) version the flow control is tied to the disposition handling, i.e. when you accept (or reject) a message, a credit is given to the client. This was changed by Robbie recently and you can either manually manage flow (by invoking `LinkEndpoint.flow()` (I guess) or use auto-acknowledgement and have vertx-proton handle flow control under the hood (then again as part of the disposition handling).

**Comment by ppatierno** [comment]
Hi Kai,

you have anticipated my last question because I have just noticed the old Vert.X Proton version.
Now it's available on Maven Central here ! 

http://search.maven.org/#artifactdetails|io.vertx|vertx-proton|3.2.0|jar

**Comment by ppatierno** [comment]
Yes I can confirm what you say because I'm using the new version in one project. You can choose to leave Vert.x Proton to handle flow control with a prefetch feature or you can disable prefetch (setPrefeth(0)) and the handling flow control manually calling flow every time you want give/increase credit to the sender.

**Comment by sophokles73** [comment]
I'll have to create a new CQ for it then so that we can remove the code from our code base and simply use it as a 3rd party dependency ...

**Comment by ppatierno** [comment]
+1

**Pull request closed without merging**
