### PR TITLE
[#3306] Change default messaging network to Kafka

### PR DESCRIPTION
**Pull request by kduba**
Signed-off-by: Kristiyan Duba <kristiyan.duba@bosch.io>

### CODE REVIEW

**Comment by kduba** [comment]
I looked throughout the code and it was like this: If AMQP is available set AMQP message provider. If Kafka is avaliable set Kafka message provider. Then use witch one is set on the Tenant level or fallback to the default configured. So FMPOV there shouldn't be any other changes to code. 

Am I missing something?

**Comment by sophokles73** [comment]
@kduba can you also please add a corresponding entry to the release notes?

**Review by sophokles73 — APPROVED** [review]
LGTM

**Comment by sophokles73** [comment]
Thanks for contributing :+1:

**Comment by sophokles73** [comment]
@kduba Can you also prepare a PR against the 2.0.x branch?

**Pull request merged**
