### PR TITLE
[#2933] Move HonoConnection related classes

### PR DESCRIPTION
**Pull request by sophokles73**
Moved HonoConnection and its implementation to amqp-connection module.
Having an additional module apart from amqp-common is necessary in order
to not introduce cyclic dependencies between modules.

This is the first PR in a series of PRs to implement #2933

### CODE REVIEW

**Comment by calohmn** [comment]
There are 2 places in the documentation where `org.eclipse.hono.client.HonoConnection` gets mentioned (in the admin guides `Hono Client Configuration` and `Secure Communication).
(The non-existing `org.eclipse.hono.client.impl.HonoClientImpl` is also mentioned there.)

**Comment by calohmn** [comment]
There is still one place in `site/documentation/content/admin-guide/secure_communication.md`.

**Comment by sophokles73** [comment]
shoot

**Comment by sophokles73** [comment]
@calohmn would you mind taking another look

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
