### PR TITLE
[#1679] Add user guide and release notes

### PR DESCRIPTION
**Pull request by kaniyan**
This is to be merged after PR #2027

### CODE REVIEW

**Comment by sophokles73** [comment]
@kaniyan can you rebase this PR?

**Comment by kaniyan** [comment]
> @kaniyan can you rebase this PR?



> @kaniyan can you rebase this PR?

@sophokles73 I have rebased.

**Comment by kaniyan** [comment]
> I find it rather confusing to have separate admin guides but a single user guide, wouldn't you agree?

@sophokles73 Initially I also thought of two separate user guides. Then I found most part of the two guides (Managing tenants, devices and credentials) remains same. Hence I took this approach. I can also create a separate user guide for the MongoDB device registry and provide link to the file based user guide to refer to the part for managing tenants, devices and credentials. WDYT?

**Comment by kaniyan** [comment]
> @kaniyan Both registry variants implement the Registry Management API, so we might be able to simply refer to the API and amend the API with the example payloads that we are currently providing in the user guide(s). WDYT?

@sophokles73 Sections  namely _Managing tenants, devices and credentials_ in Device Registry user guide are repetitive with the API docs. It is a good idea to refer to the Registry Management API. As you suggested I would create a separate user guide for the MongoDB registry and refer the Management API there in this PR. 

For amending the API with examples we have an issue #1367 open. I would suggest a separate PR for amending the API with more examples.

**Comment by sophokles73** [comment]
@kaniyan sounds good :+1:

**Comment by kaniyan** [comment]
@sophokles73 As we discussed above, I have now created a separate user guide for the MongoDB based device registry. Also I have referred to the Device Registry Management API page for the sections on how to manage tenants, devices and credentials. Please take a look.

**Pull request merged**
