### PR TITLE
Example device registry overwrites existing config when restarting in openshift

### PR DESCRIPTION
**Pull request by BobClaerhout**
Fix for issue https://github.com/eclipse/hono/issues/1007

### CODE REVIEW

**Comment by ctron** [comment]
Thanks for the PR, that was quick :smile: 

In order for the IP check to succeed, you will need to add `Signed-off-by:` at the end of the git commit message. You will need to amend the current git commit and "force push" it to this PR.

You will need to use an e-mail address for which you signed the Eclipse Contributor Agreement (ECA): https://www.eclipse.org/legal/ECA.php

**Comment by sophokles73** [comment]
@BobClaerhout you may also want to take a look at out [Contributing guide](https://github.com/eclipse/hono/blob/master/CONTRIBUTING.md) :-)

**Comment by BobClaerhout** [comment]
Ok, is there anything I can/must do to get this PR merged?

**Comment by ctron** [comment]
> Ok, is there anything I can/must do to get this PR merged?

Nope, I will take care of this …

**Comment by ctron** [comment]
@BobClaerhout Could you please rebase the PR once more.

**Comment by BobClaerhout** [comment]
@ctron A rebase doesn't change anything. I forked this morning and had every change from the master: https://github.com/eclipse/hono/compare/master...BobClaerhout:OverwriteExistingDeviceRegistryConfig

**Pull request merged**
