### PR TITLE
Create tenant CA for DEFAULT_TENANT.

### PR DESCRIPTION
**Pull request by b-abel**
The example device cert is no longer issued by Hono's "server" CA.
Instead the script creates a separate CA for the tenant and issues
the client certificate from it.

Signed-off-by: Abel Buechner-Mihaljevic <Abel.Buechner@bosch-si.com>

### CODE REVIEW

**Comment by sophokles73** [comment]
@b-abel can you please rebase your PR so that the Travis build has a chance of succeeding?

**Comment by b-abel** [comment]
Done.

**Comment by sophokles73** [comment]
can we also use this for the integration tests where we check authentication of a device using a client certificate?

**Comment by b-abel** [comment]
@sophokles73 I don't see why it would not be possible to load the cert in the test. But currently the tests use random tenant and device IDs, which needs to be changed then.

**Comment by sophokles73** [comment]
yeah, didn't think of that. We can maybe later change that ...

**Pull request merged**
