### PR TITLE
Upgrade to Quarkus 2.8

### LINKED ISSUE #3219: Upgrade to latest Quarkus 2.8 release

### PR DESCRIPTION
**Pull request by sophokles73**
fixes #3219

### CODE REVIEW

**Comment by calohmn** [comment]
It seems the failing test `testScenarioWithPartitionRevokedWhileHandlingIncomplete()` in `AsyncHandlingAutoCommitKafkaConsumerTest` will be fixed with the changes made in #3223 (adding `consumer.addOnKafkaConsumerReadyHandler(readyTracker);` and waiting on the `readyTracker`).

**Comment by sophokles73** [comment]
@calohmn so you are suggesting to merge this PR once #3223 has been merged, right?

**Comment by calohmn** [comment]
@sophokles73 yes

**Comment by calohmn** [comment]
The `DropHttpRequestSpansSampler` class needs to be adapted here.
In the `shouldSample` method, the `.substring(1)` part needs to be removed, along with the comment in the line above.
See https://github.com/quarkusio/quarkus/pull/24017#issuecomment-1054829789.

**Comment by sophokles73** [comment]
Ok, I will apply that change

**Comment by sophokles73** [comment]
> It seems the failing test testScenarioWithPartitionRevokedWhileHandlingIncomplete() in AsyncHandlingAutoCommitKafkaConsumerTest will be fixed with the changes made in https://github.com/eclipse/hono/pull/3223

@calohmn doesn't seem to be the case. Any idea why the checkpoint is being flagged more than once?

**Comment by calohmn** [comment]
> doesn't seem to be the case. Any idea why the checkpoint is being flagged more than once?

@sophokles73 It seems to me like a general issue with the test. I'm looking into a fix. I don't currently see how this is related with the Quarkus update.

**Comment by calohmn** [comment]
The issue with the `testScenarioWithPartitionRevokedWhileHandlingIncomplete` test seems to be, that the `OnPartitionsAssignedHandler` declared at the bottom of the test is not only run on the last rebalance, but sometimes also already on the rebalance before that.

Replacing `mockConsumer.rebalance(List.of(TOPIC2_PARTITION));` in line 793 with
```
        final CountDownLatch rebalanceWithTopic2Done = new CountDownLatch(1);
        consumer.setOnPartitionsAssignedHandler(partitions -> {
            rebalanceWithTopic2Done.countDown();
        });
        mockConsumer.rebalance(List.of(TOPIC2_PARTITION));
        rebalanceWithTopic2Done.await();
```
should fix the issue, making sure that the bottom `OnPartitionsAssignedHandler` is only run after the *last* rebalance, as intended by the test.

**Comment by sophokles73** [comment]
ok, I will give it a shot

**Comment by calohmn** [comment]
The failing test is actually due to the newer Vert.x version being used here.
The `Strict checkpoint flagged too many times` check has only been introduced in Vert.x 4.2.6 (see https://github.com/eclipse-vertx/vertx-junit5/issues/113).

**Review by calohmn — APPROVED** [review]
LGTM
Follow-up commits/PRs could then address re-enabling of parallel unit-test execution and removal of added vert.x traces for event bus messages (they are not useful IMHO).

**Comment by sophokles73** [comment]
> removal of added vert.x traces for event bus messages (they are not useful IMHO).

@calohmn can you point me to the corresponding code?

**Comment by calohmn** [comment]
> @calohmn can you point me to the corresponding code?

It's about traces created by means of the Quarkus [EventBusInstrumenterVertxTracer](https://github.com/quarkusio/quarkus/blob/2.8/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/EventBusInstrumenterVertxTracer.java) (e.g. `notification.tenant-change-v1 send` or `authentication.in send`). 
Since usage of this instrumenter isn't configurable, it seems the only way to drop these traces is in a way similar to the `DropHttpRequestSpansSampler`.
I'm already looking into creating a PR for this.

**Comment by sophokles73** [comment]
ok, I am working on a PR for re-enabling parallel test execution ...

**Pull request merged**
