### PR TITLE
Upgrade to vert.x 4.1.3 and Quarkus 2.2.2

### PR DESCRIPTION
**Pull request by sophokles73**
This addresses #2805

This is basically the same as PR #2806 but uses vert.x 4.1.3, Quarkus 2.2.2 and Infinispan 12.1.7 instead.
As @dejanb had pointed out in the Hono chat on Gitter, Quarkus 2.2 is a long term support release so it seems preferable to use 2.2 instead of 2.0.

I do have another PR for replacing the deprecated ConfigProperties class usage which also addresses #2831.

### CODE REVIEW

**Comment by sophokles73** [comment]
I have created [CQ23718](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23718) for the *infinispan-core* artifact's license check.

**Comment by sophokles73** [comment]
@dejanb any objections to merging this one?

**Comment by sophokles73** [comment]
@calohmn would you mind taking a final look?

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
