### PR TITLE
[#926] Support authorization of multiple gateways per device.

### PR DESCRIPTION
**Pull request by sophokles73**
Device registration service now supports multiple gateway identifiers to
be specified in a device's registration information's "via" property.
The "via" property can be set to either a string or a JSON array of
strings.

### CODE REVIEW

**Comment by sophokles73** [comment]
@BobClaerhout is this extension useful for your use cases? Note, though, that this PR does not allow the device registry nor applications to determine, via which particular gateway a device is *currently* connected. For that, we have #930 in the pipeline ...

**Comment by BobClaerhout** [comment]
We bypassed the gateway feature because we do not know which gateway will be sending the messages for a specific device (i.e.: we have a pool of devices and a pool of gateways on premise which send data for the devices). However, currently hono does not know of the actual devices because only one gateway was possible per device. Now it gets tricky: this means that the physical gateway is actually  a device in hono. Which gateway has received which device last, is currently kept in the business application to make sure to send downlink commands to the correct hono device/physical gateway. This PR is a step in the right direction for us.

**Comment by sophokles73** [comment]
> This PR is a step in the right direction for us.

Does this mean that you then would not need to *bypass the gateway feature* altogether anymore?

**Comment by BobClaerhout** [comment]
@sophokles73 Eventually, yes. The real benefit for us is https://github.com/eclipse/hono/issues/930 as we no longer have to keep the latest gateway-device combination in our business application.
However, we also think it would be a lot more easier to configure if we could configure a pool of gateways for a device instead of a list of gateways for each device. This will allow us to add/remove gateways without having to persist this for each device. Ultimately a pool of gateways ways can refer to other pools to make this as dynamical as possible (e.g.: some devices roaming to other gateway pools).

**Pull request merged**
