### PR TITLE
fix loading of loriot provider when using quarkus images

### PR DESCRIPTION
**Pull request by JeffreyThijs**

### CODE REVIEW

**Comment by calohmn** [comment]
@JeffreyThijs Thanks for contributing!

Is it, that this contribution is done under the copyright of Aloxy? Otherwise you could add yourself to the *Copyright Holders* section of `legal/src/main/resources/legal/NOTICE.md`.

**Comment by JeffreyThijs** [comment]
> @JeffreyThijs Thanks for contributing!
> 
> Is it, that this contribution is done under the copyright of Aloxy? Otherwise you could add yourself to the _Copyright Holders_ section of `legal/src/main/resources/legal/NOTICE.md`.

Yes, this is done under the copyright of Aloxy. Always happy to help!

**Review by calohmn — APPROVED** [review]
LGTM

**Comment by sophokles73** [comment]
@calohmn IMHO this should also be applies to the 1.10.x branch ...

**Comment by calohmn** [comment]
Yes, I've just done that. This complements the other, more general fix for the Quarkus-based LoRa adapter in 1.10.1.

**Pull request merged**
