### PR TITLE
[#2809] Prevent unhandled MongoDB client exceptions

### LINKED ISSUE #2809: MongoDB Device Registry: IllegalStateException on close
When the MongoDB device registry component is shut down, there may be exceptions like this in the log:
```
WARN org.eclipse.hono.tracing.TracingHelper An unexpected error occurred!
java.lang.IllegalStateException: state should be: server session pool is open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:70)
	at com.mongodb.internal.session.ServerSessionPool.get(ServerSessionPool.java:79)
	at com.mongodb.internal.session.BaseClientSessionImpl.<init>(BaseClientSessionImpl.java:40)
	at com.mongodb.async.client.ClientSessionImpl.<init>(ClientSessionImpl.java:49)
	at com.mongodb.async.client.ClientSessionHelper.createClientSession(ClientSessionHelper.java:102)
	at com.mongodb.async.client.ClientSessionHelper.createClientSession(ClientSessionHelper.java:66)
	at com.mongodb.async.client.ClientSessionHelper.withClientSession(ClientSessionHelper.java:51)
	at com.mongodb.async.client.OperationExecutorImpl.execute(OperationExecutorImpl.java:66)
	at com.mongodb.async.client.FindIterableImpl.first(FindIterableImpl.java:198)
	at io.vertx.ext.mongo.impl.MongoClientImpl.findOne(MongoClientImpl.java:312)
	at org.eclipse.hono.deviceregistry.mongodb.model.MongoDbBasedTenantDao.getById(MongoDbBasedTenantDao.java:208)
	at org.eclipse.hono.deviceregistry.mongodb.model.MongoDbBasedTenantDao.getById(MongoDbBasedTenantDao.java:200)
	at org.eclipse.hono.deviceregistry.mongodb.service.DaoBasedTenantInformationService.tenantExists(DaoBasedTenantInformationService.java:74)
	at org.eclipse.hono.deviceregistry.service.device.AbstractDeviceManagementService.readDevice(AbstractDeviceManagementService.java:135)
	at org.eclipse.hono.service.management.device.DelegatingDeviceManagementHttpEndpoint.lambda$doGetDevice$0(DelegatingDeviceManagementHttpEndpoint.java:151)
	at io.vertx.core.Future.lambda$compose$3(Future.java:368)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
	at io.vertx.core.impl.FutureImpl.onComplete(FutureImpl.java:83)
	at io.vertx.core.impl.CompositeFutureImpl.onComplete(CompositeFutureImpl.java:130)
	at io.vertx.core.impl.CompositeFutureImpl.onComplete(CompositeFutureImpl.java:25)
	at io.vertx.core.Future.compose(Future.java:364)
	at io.vertx.core.Future.compose(Future.java:336)
	at org.eclipse.hono.service.management.device.DelegatingDeviceManagementHttpEndpoint.doGetDevice(DelegatingDeviceManagementHttpEndpoint.java:149)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:125)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:38)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:525)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:511)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
[...]
```
To avoid confusion, such cases should be handled in a better way.

### PR DESCRIPTION
**Pull request by calohmn**
This fixes #2809.

### CODE REVIEW

**Review by sophokles73 — COMMENTED** [review]
I do not seem to understand why we need the Futures.wrap() method. Don't the invocations of the MongoClient methods already return a failed future if something goes wrong and we can simply handle it in the Future.recover() function?

**Comment by calohmn** [comment]
Right, I misinterpreted the stacktrace here.

**Comment by calohmn** [comment]
I've removed the changes wrapping the MongoDB client operation now. 
Instead, the existing `mapError` method has been adapted and a new `logError` method has been added.

**Review by kaniyan — APPROVED** [review]
LGTM

**Pull request merged**
