### PR TITLE
Add MongoDbBasedRegistrationService

### PR DESCRIPTION
**Pull request by calohmn**
Adds a RegistrationService implementation based on MongoDB.

Implementation is kept in the new Maven module "/registration/mongodb".

In the "hono-app" module, this implementation can be included in the build via a "registration-mongodb" Maven profile.

When the "registration-mongodb" Maven profile is used for building the complete hono projects, the target directory of the example module will contain an adapted "docker-compose.yml" that starts and uses a MongoDB container.

### CODE REVIEW

**Comment by calohmn** [comment]
Added MongoDB configuration POJO (with additional "collection" property) and made POM corrections.

**Comment by calohmn** [comment]
Rebased and resolved merge conflicts.

**Comment by sophokles73** [comment]
@calohmn, do you want to keep this PR open? I assume it would make more sense to create a new one based on the current master, wouldn't it?

**Comment by calohmn** [comment]
Yes, better to create a new PR then.

**Pull request closed without merging**
