### PR TITLE
[#3090] Remove Spring Boot based MQTT adapter

### LINKED ISSUE #3090: Remove Spring Boot based MQTT adapter

### PR DESCRIPTION
**Pull request by sophokles73**
Fixes #3090

### CODE REVIEW

**Comment by calohmn** [comment]
`/adapter-base-spring/ ` should be removed from `CODEOWNERS`.

In the `hono-adapter-base` pom there is still a `<artifactId>spring-security-crypto</artifactId>` dependency defined - I guess that's not needed anymore.

The deployment yaml example in `site/documentation/content/deployment/resource-limitation.md` is still Spring specific. It could be adapted as well.

**Comment by sophokles73** [comment]
> In the hono-adapter-base pom there is still a <artifactId>spring-security-crypto</artifactId> dependency defined - I guess that's not needed anymore.

That is still needed, we use it to verify password hashes.

**Comment by sophokles73** [comment]
> In the hono-adapter-base pom there is still a <artifactId>spring-security-crypto</artifactId> dependency defined - I guess that's not needed anymore.

That is still needed, we use it to verify password hashes.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
