### PR TITLE
enable set maxInstances independent from processor count

### PR DESCRIPTION
**Pull request by rpahli**
We run hono on kubernetes and the cpu usage is currently not very hight, and we want to increase the vertx instances but this is not possible because of the processor count check.

### CODE REVIEW

**Comment by sophokles73** [comment]
Rico,

can you elaborate a little on what you mean *CPU usage is not very high*, i.e. how many CPU shares does your POD get (requests, limits) and how much of that is actually used? I am asking because I find it rather difficult to identify the number of verticle instances being the limiting factor here. My experiments on real hardware seem to indicate that vert.x is quite good at utilizing CPU if there is enough workload.

Kai

**Comment by sophokles73** [comment]
@rpahli any news on this?

**Comment by rpahli** [comment]
Sry I was busy,

 I try to start a hono adapter without any limitations on kubernetes but the adapter used only one cpu. That's the reason I want to override the cpu by myself but the CPU check limits me.

**Comment by sophokles73** [comment]
> I try to start a hono adapter without any limitations on kubernetes but the adapter used only one cpu.

How many cores does the Kubernetes node have that the adapter pod got scheduled on?
Did you set *maxInstances* to 0?

**Comment by rpahli** [comment]
> > I try to start a hono adapter without any limitations on kubernetes but the adapter used only one cpu.
> 
> How many cores does the Kubernetes node have that the adapter pod got scheduled on?
> Did you set _maxInstances_ to 0?

Yes I tryed it with 0 and the node has 2 cores.

**Comment by sophokles73** [comment]
> Yes I tryed it with 0 and the node has 2 cores.

Ok, and what did you expect to happen then when you started publishing messages to the adapter?

**Comment by rpahli** [comment]
@sophokles73 sry for the late replay. We have now a solution which fit's for us. I think we can close the PR.

**Comment by sophokles73** [comment]
@rpahli may I ask how your solution looks like? Maybe others would be interested to know as well ...
You can, of course, close this issue whenever you want as you opened it in the first place.

**Pull request closed without merging**
