### PR TITLE
[#643] Integrate the AMQP adapter in the example deployment

### PR DESCRIPTION
**Pull request by Alfusainey**
@sophokles73: This patch integrates the amqp adapter in the example deployment.

Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>

### CODE REVIEW

**Comment by sophokles73** [comment]
@Alfusainey can you rebase this PR to current master? I think I have found (and fixed) the issue with the unstable AMQP integration tests ...

**Comment by Alfusainey** [comment]
> unstable AMQP integration tests ...

AMQP or MQTT?

**Comment by Alfusainey** [comment]
@sophokles73: done!

**Comment by Alfusainey** [comment]
> what about Kubernetes and OpenShift?

ok, right away!

**Comment by sophokles73** [comment]
@Alfusainey any progress on this?

**Comment by Alfusainey** [comment]
@sophokles73: sure. i made two new commits. 505399d (k8s deployment) and db9c134 (openshift).

**Comment by sophokles73** [comment]
@Alfusainey have you actually tried to deploy to a local Swarm, Minikube and Minishift?

**Comment by sophokles73** [comment]
@Alfusainey you might also consider adding AMQP adapter specific information to the Kubernetes and OpenShift Deployment guides, e.g. adding the AMQP adapter to the Services list etc.

**Comment by Alfusainey** [comment]
> @Alfusainey have you actually tried to deploy to a local Swarm, Minikube and Minishift?

I only tested on docker swarm and minikube as i was having some issues installing Minishift. I will do that today. yes, i will update the deployment section of the docs.

**Comment by Alfusainey** [comment]
@sophokles73: am now getting a strange error when deploying on minikube:

> error: unable to recognize "hono/deploy/target/deploy/resource-descriptors/dispatch-router/dispatch-router-route.yaml": no matches for kind "Route" in version "v1"

it happens to all services except the `artemis broker` and `grafana`. i tested this on the master branch which does not include my changes.

> minikube version: v0.28.0

kubectl version

> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Any idea why this is happening?

**Comment by sophokles73** [comment]
> Any idea why this is happening?

This is because kubernetes does not support *Route*s. This is OpenShift specific. You can simply ignore this ...

**Comment by Alfusainey** [comment]
@sophokles73: i am really having a hard time getting the deployment of enmasse on minishift to work.. Only 6 out of the 8 pods are running. the `mqtt-lwt` service fails frequently:

> Error: The container mqtt-lwt is crashing frequently. It must wait before it will be restarted again.

The `mqtt-lwt` pod is especially problematic.. it starts up correctly, then fail, then starts correctly and fail again..

The `qdrouterd` also has a problem starting up:

> Warning: The pod has been stuck in the pending state for more than five minutes.

I also notice that my local minishift VM aborts automatically (i dont know why) and have to restart it every now and then..

if i try to deploy using the openshift deploy script, it gets stuck with `Waiting for EnMasse...
6/8 up` and times out after sometime. thus running the deployment script with only 6 services up does not work.

Have you experience this on your side? any idea why this is happening? I am following the instructions outlined in the `OpenShift with EnMasse` deployment on the website

**Comment by sophokles73** [comment]
@Alfusainey if it works on Kubernetes, just undo your changes to the OpenShift deployment script and we merge the PR with only Swarm and Kubernetes support.

@ctron @ppatierno Deployment to OpenShift has never been as straightforward as the Kubernetes deployment but it seems that we are really stuck here at the moment. So, if you would like to add the AMQP adapter to the OpenShift deployment, feel free to give it a shot later.

**Comment by Alfusainey** [comment]
@sophokles73 thanks! i rebased and updated the PR to remove the openshift deployment and modified the `kubernetes` deployment docs

**Pull request merged**
