### PR TITLE
Fix broken doc links

### PR DESCRIPTION
**Pull request by dejanb**

### CODE REVIEW

**Comment by sophokles73** [comment]
@dejanb When I run a Hugo server for the documentation locally on master, these links all work fine for me. Why do you think they are broken?

**Comment by dejanb** [comment]
@sophokles73 They are failing my local build 

```
Going to build documentation in directory: /Users/dejanb/workspace/oss/hono/site/target/docs
INFO 2020/06/25 11:20:03 Using config file:
Building sites … INFO 2020/06/25 11:20:03 syncing static files to /Users/dejanb/workspace/oss/hono/site/target/docs/
INFO 2020/06/25 11:20:03 found taxonomies: map[string]string{"category":"categories", "tag":"tags"}
WARN 2020/06/25 11:20:03 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/06/25 11:20:03 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
WARN 2020/06/25 11:20:03 Page's .UniqueID is deprecated and will be removed in a future release. Use .File.UniqueID.
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/http-adapter.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/coap-adapter.md": page not found
WARN 2020/06/25 11:20:03 "/Users/dejanb/workspace/oss/hono/site/documentation/content/admin-guide/mongodb-device-registry-config.md:1:1": make non-relative ref/relref page reference(s) in page %q absolute, e.g. {{< ref "/blog/my-post.md" >}}
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/tenancy.md" from page "api/tenant/index.md": page not found
WARN 2020/06/25 11:20:03 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/http-adapter.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/coap-adapter.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/tenancy.md" from page "api/tenant/index.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "concepts/device-notifications.md" from page "dev-guide/java_client_consumer.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/tenancy.md" from page "api/tenant/index.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/http-adapter.md": page not found
ERROR 2020/06/25 11:20:03 [en] REF_NOT_FOUND: Ref "/concepts/command-and-control.md" from page "user-guide/coap-adapter.md": page not found
Total in 225 ms
Error: Error building site: logged 15 error(s)
```

And these files don't physically exists anymore.

**Comment by sophokles73** [comment]
Hmm, this is my local build output:
```
[INFO] --- exec-maven-plugin:1.6.0:exec (default) @ hono-site ---
Hugo Static Site Generator v0.73.0 linux/amd64 BuildDate: 2020-06-23T20:37:55Z
Going to build homepage in directory: /home/hak8fe/git/hono/site/target
INFO 2020/06/25 13:29:01 Using config file: 
Building sites … INFO 2020/06/25 13:29:01 syncing static files to /home/hak8fe/git/hono/site/target/
WARN 2020/06/25 13:29:01 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.

                   | EN  
-------------------+-----
  Pages            | 19  
  Paginator pages  |  0  
  Non-page files   |  3  
  Static files     | 36  
  Processed images |  0  
  Aliases          |  3  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 87 ms
Going to build documentation in directory: /home/hak8fe/git/hono/site/target/docs
INFO 2020/06/25 13:29:01 Using config file: 
Building sites … INFO 2020/06/25 13:29:01 syncing static files to /home/hak8fe/git/hono/site/target/docs/
WARN 2020/06/25 13:29:01 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/06/25 13:29:01 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
WARN 2020/06/25 13:29:01 Page.UniqueID is deprecated and will be removed in a future release. Use .File.UniqueID
WARN 2020/06/25 13:29:01 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

                   | EN  
-------------------+-----
  Pages            | 73  
  Paginator pages  |  0  
  Non-page files   | 58  
  Static files     | 97  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 236 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.758 s
[INFO] Finished at: 2020-06-25T13:29:01+02:00
[INFO] ------------------------------------------------------------------------
```

Are you using the Maven build? Which Hugo version are you using?

**Comment by dejanb** [comment]
It works with upgraded Hugo. I don't see however, why we wouldn't upgrade to the updated file names?

**Comment by sophokles73** [comment]
I didn't say that we shouldn't change the names. I was just curious why this failed for you while it didn't for me :-)

**Pull request merged**
