### PR TITLE
Update to Artemis 2.13.0, Qpid router 1.14.0 image versions

### PR DESCRIPTION
**Pull request by calohmn**
Update to latest image versions for use in the integration tests.

### CODE REVIEW

**Comment by sophokles73** [comment]
we will also need to assure license compatibility for the new Dispatch Router and Artemis versions ...

**Comment by sophokles73** [comment]
@calohmn I have seen that you have created CQs for Artemis and Dispatch Router. However, I couldn't find CQs for Artemis' transitive dependencies. We will also need those ....

**Comment by calohmn** [comment]
@sophokles73 I checked the transitive dependencies of Artemis 2.13.0 and found no relevant changes compared to the Artemis version used in Hono up to now.

**Comment by calohmn** [comment]
CQs have been resolved now.

**Comment by sophokles73** [comment]
Did you run the dash-license tool successfully?

**Comment by calohmn** [comment]
Running the dash-license tool on the Hono dependencies extracted via `mvn dependency:list` obviously doesn't show any difference since there are no maven dependencies for Artemis and the Qpid router in Hono.
Running the dash-license tool on the artemis-distribution module maven dependencies also shows no difference. It seems the Artemis 2.13.0 maven coordinates don't get matched with the Artemis CQ created as part of this PR (most of them get matched with ClearlyDefined though, e.g. artemis-server).
So, I guess the dash-license tool isn't of much help here.

**Comment by calohmn** [comment]
@sophokles73 
Checked out tag 2.13.0 of the artemis repo.
$ cd activemq-artemis/artemis-distribution
$ mvn dependency:list | grep -Poh "\S+:(runtime|compile)" | sort | uniq > _maven_rt_compile_2.13.0.deps
$ java -jar <path>/org.eclipse.dash.licenses-0.0.1-SNAPSHOT.jar _maven_rt_compile_2.13.0.deps 

Then the corresponding steps for tag 2.10.1.

The output for 2.13.0 has added/changed dependencies only for "org.apache.activemq/*artemis*" entries (except "org.apache.activemq/activemq-branding").

**Comment by sophokles73** [comment]
I did the same thing and it looks like we have CQs for all of the non-artemis components on record which are part of the artemis Docker image.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
