### PR TITLE
[#557] Pipeline script for Hono-CI jenkins build job

### PR DESCRIPTION
**Pull request by kaniyan**
With reference to #557,  all the jenkins build jobs are to be implemented as pipelines. To start with, jenkins [Hono-CI](https://ci.eclipse.org/hono/job/Hono-CI/) build job is to be implemented as a pipeline. This PR contains respective pipeline scripts.

Below screen shot is from a local jenkins after deploying above scripts:
image

### CODE REVIEW

**Comment by ctron** [comment]
I think it would make sense to also add the jacoco code coverage files from the build.

**Comment by kaniyan** [comment]
@ctron I created Hono-CI pipeline based on the already available Jenkins job configuration and currently code coverage results are not available there. I agree with you, that it makes sense to include them. I will add them to the Hono-CI pipeline. 

[Jacoco jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin) is not installed by default in Eclipse Jenkins server  [Refer: Plugins-list](http://wiki.eclipse.org/Jenkins).  I don't have access to Jenkins settings to install it.  Could someone with access rights kindly install it? @ctron @pellmann @sophokles73 @sysexcontrol

**Comment by ctron** [comment]
> Jacoco jenkins plugin is not installed by default in Eclipse Jenkins server

I wasn't aware of this. I will file a request for that.

**Comment by ctron** [comment]
Version 3.0.3 of the Jacoco plugin should be installed.

**Comment by kaniyan** [comment]
@ctron Added jacoco code coverage files from the build.

**Comment by sophokles73** [comment]
The pipeline succeeds to build Hono now [1]. However, there seems to be a problem with the code coverage trend collection...

[1] https://ci.eclipse.org/hono/job/Hono%20CI%20Pipeline/

**Pull request merged**
