### PR TITLE
Abstract credentials test race condition

### PR DESCRIPTION
**Pull request by jbtrystram**
The credentials tests did not wait for the credential registration to be complete before retrieving the data.

### CODE REVIEW

**Comment by jbtrystram** [comment]
in the process of writing that fix, I realised that there is a lot of redundancy in those tests.
Basically a test will add the credential to the registry, then get/delete/update it.

So we could factor the credential insertion in a `@BeforeEach` method. The issue here is that when extending a test class, if the extending class also defines a `@BeforeEach` method, then it's executed *before* the parent class' one. 
Typically, the extending class would spin up the device registry then run the tests. So using a `@BeforeEach` class here wouldn't work. Alternatively we could define an abstract method that must be implemented as the `BeforeEach` method in the extending classes. But it may be weird

**Comment by ctron** [comment]
What would happen when the handler set by `setHandler` gets called with a *failed* result?

**Comment by jbtrystram** [comment]
test fails : 
```
 svc.add("tenant", data, ctx.succeeding(s -> ctx.verify(() -> {
            assertEquals(HttpURLConnection.HTTP_CREATED, s.getStatus());
            future.complete();
        })));
```
the VertxTestContext expect a success on the assertion following the `add` operation.

**Comment by ctron** [comment]
But for the following:

~~~java
registration.setHandler(r-> {});
~~~

I don't see any check there. The handler would always be called, not matter if the registration was successful or not.

**Comment by jbtrystram** [comment]
Does the execution carry through even if the context is already failed ?

**Comment by dejanb** [comment]
@jbtrystram I wouldn't bother with moving register() into `@BeforeEach`. This way is actually clearer what's being tested.

**Comment by jbtrystram** [comment]
@ctron Completing the future with the `RegistrationResult` then 
```
        registration.setHandler(r-> {
           if ( ((RegistrationResult) r).isOk() ) {
                    // carry on...
           }
      });
```
WDYT ?

**Comment by dejanb** [comment]
> WDYT ?

I was looking into this and the test stops properly on the first failure. I don't think we need extra checks.

**Comment by jbtrystram** [comment]
> > WDYT ?
> 
> I was looking into this and the test stops properly on the first failure. I don't think we need extra checks.

nice. That was I assumed but i didn't double checked. Thanks :)

**Pull request merged**
