### PR TITLE
[#3089] Remove Kura protocol adapter

### LINKED ISSUE #3089: Remove Kura protocol adapter
The Kura adapter has been long deprecated and marked for removal in Hono 2.0.0

### PR DESCRIPTION
**Pull request by sophokles73**
The Kura adapter code has been removed. The Kura adapter's User and
Admin Giudes have been marked as hidden in order to still allow for old
links to find its target.

Fixes #3089

### CODE REVIEW

**Comment by calohmn** [comment]
I think `org.eclipse.hono.util.Constants#PROTOCOL_ADAPTER_TYPE_KURA` can be removed too.
Did you keep the kura-adapter demo-cert creation code on purpose?
I think a short note in der Kura user/admin guide about the Kura adapter not being available in Hono >= 2.0 would be good - in case users have indeed followed an old link without a specific Hono version in it.

**Comment by sophokles73** [comment]
> Did you keep the kura-adapter demo-cert creation code on purpose?

No, I will remove that as well along with the keys/certs

**Comment by sophokles73** [comment]
> I think org.eclipse.hono.util.Constants#PROTOCOL_ADAPTER_TYPE_KURA can be removed too.

Yes, will do

**Comment by sophokles73** [comment]
> I think a short note in der Kura user/admin guide about the Kura adapter not being available in Hono >= 2.0 would be good - in case users have indeed followed an old link without a specific Hono version in it.

Good idea

**Comment by calohmn** [comment]
There are also two "kura" occurrences in the "deploy" folder ("services.sh" and sandbox config).

**Comment by sophokles73** [comment]
> There are also two "kura" occurrences in the "deploy" folder ("services.sh" and sandbox config).

FMPOV we should keep both occurrences. The former one might be helpful when dealing with deployments that (still) include the Kura adapter. The latter one is due to the fact that the Hono Helm chart still supports the Kura adapter.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
