### PR TITLE
[#3101] Remove Spring Boot based Authentication server

### LINKED ISSUE #3101: Remove Spring Boot based Authentication service

### PR DESCRIPTION
**Pull request by sophokles73**
Fixes #3101

### CODE REVIEW

**Comment by sophokles73** [comment]
@kaniyan would you mind taking a look?

**Comment by kaniyan** [comment]
https://github.com/eclipse/hono/blob/819c152bc6d0619810afc8c1145f942cff785323/site/documentation/content/admin-guide/secure_communication.md?plain=1#L218

In the above guide, we still refer to the image  _eclipse/hono-service-auth_.

**Comment by sophokles73** [comment]
The guide explains how to configure and use OpenSSL with the Docker images. There is an even bigger problem with this guide: it does not seem to work with the Quarkus based images anymore at all . I have created #3107 for tracking this problem. However, I do not think that it affects this PR.

**Review by kaniyan — APPROVED** [review]
LGTM

**Pull request merged**
