### PR TITLE
[#454] Fix memory leak in TelemetrySenderImpl and EventSenderImpl

### PR DESCRIPTION
**Pull request by ctron**
This effectively fixes the memory leak for me. But I am not sure if this is the right solution.

@dejanb: Could you check if this is the way to fix this?!

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by sophokles73** [comment]
I am afraid that this problem also exists in Hono Messaging. In particular in `org.eclipse.hono.event.impl.ForwardingEventDownstreamAdapter` where we *forward* the messages received from the protocol adapter to the downstream AMQP 1.0 network. I think we will need to properly settle the downstream messages there as well instead of just forwarding the disposition update received from downstream to the upstream protocol adapter.

**Comment by ctron** [comment]
I did check this as well. Because I did expect the same issue to be present there. However, I could not see any memory leak. Maybe I didn't look thoroughly enough.

**Comment by sophokles73** [comment]
Maybe you just looked at the `ForwardingTelemetryDownstreamAdapter`. We do not have an issue there because we are not providing a disposition handler in the call to send the message downstream. Thus, auto settling kicks in. But I am pretty sure that we do have the problem when forwarding events because there we *do* provide a disposition handler.

**Comment by ctron** [comment]
You are right, I did not check that one. And as I am only testing with telemetry data at the moment, I won't be able to see a memory leak in action.

I will amend this PR to add this as well.

**Comment by dejanb** [comment]
I think the root cause of this is that ProtonSender is not in auto-settle mode by default, although it should be by default

https://github.com/vert-x3/vertx-proton/blob/master/src/main/java/io/vertx/proton/ProtonSender.java#L100

We should be able to achieve the same by setting explicitly 

`sender.setAutoSettle(true);`
 after creating a sender at https://github.com/eclipse/hono/blob/master/client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java#L177

and fix ProtonSenderImpl in the future versions

https://github.com/vert-x3/vertx-proton/blob/master/src/main/java/io/vertx/proton/impl/ProtonSenderImpl.java#L37

We can test this tomorrow

**Comment by sophokles73** [comment]
ProtonSenderImpl actually sets autoSettle to `true` on a delivery created when a message is sent without specifying a disposition handler

https://github.com/vert-x3/vertx-proton/blob/edb0d68199020fddbd75312d883528d1a6b444aa/src/main/java/io/vertx/proton/impl/ProtonSenderImpl.java#L102

However, I agree that we should
1. fix this in upstream vertx-proton
2. explicitly enable auto-settle on the senders we create as suggested by @dejanb (nice work analyzing this :+1: )

**Comment by sophokles73** [comment]
Created upstream PR: https://github.com/vert-x3/vertx-proton/pull/63

**Pull request merged**
