### PR TITLE
Provide some of the missing sequence diagrams.

### PR DESCRIPTION
**Pull request by sysexcontrol**
Since quite some time we have sequence diagrams announced in the documentation, but did not provide any.
I made some first versions of the IMHO most missing diagrams (mandatory operations of APIs e.g.).
Please have a look and provide feedback - this is just a draft, but should provide new users of hono a quick way of understanding about how some internals work.

As a proposal, I placed the source code of the sequence diagrams inside the new "site/diagrams" folder, so changes can be made quicker without the need to recreate a sequence diagram if you do not have the source yourself.

WDYT?

### CODE REVIEW

**Comment by sophokles73** [comment]
where do you want to add these diagrams?

**Comment by sysexcontrol** [comment]
The two diagrams for the API calls have a place already (currently: 

> TODO add sequence diagram

The third one (Protocol adapter device authentication) : IMHO should be splitted into two, one for the MQTT PA and one for the REST PA, after we basically agree on the mechanisms). And then added to the corresponding section about the PA.

But maybe you have a better idea where to put this? AFAIK we do not have a proper place for them so far, do we?
WDYT?

**Comment by sophokles73** [comment]
> The two diagrams for the API calls have a place already

assuming you are referring to *assert registration* and *get* (credentials), I think that the sequence diagrams should **not** include any of the concrete components of Hono, in particular none of the demo implementations. These sequence diagrams are only supposed to illustrate how a client interacts with the API, i.e. *any arbitrary* implementation of the API. Therefore, I'd rather not have any other components show up as lifelines in the diagrams. If we want to illustrate how Hono is (currently) implemented, then we could add these diagrams to the *Architecture* section ...

**Comment by sysexcontrol** [comment]
@sophokles73 : Thanks for the good comments - focussed on the Credentials API I provided more generic sequence diagrams now, already integrated in the documentation pages.

Can you please do a focussed review of the Credentials API sequence diagrams of the second commit if that more matches what we should describe?

If we agree on this level, I will provide more diagrams for both APIs (credentials and registration API) in separate PRs. This PR should only be for discussion and will probably be closed without merge afterwards.

**Comment by sysexcontrol** [comment]
@sophokles73 : Thanks for the good comments - focussed on the Credentials API I provided more generic sequence diagrams now, already integrated in the documentation pages.

Can you please do a focussed review of the Credentials API sequence diagrams of the second commit?

**Comment by sysexcontrol** [comment]
@sophokles73 : sequence diagrams for Credentials API updated, can you have a look again?
This would be the style of the other sequence diagrams then....
Thx!

**Comment by sysexcontrol** [comment]
Thanks for all input - I will now create PRs for the APIs and possibly one for architecture sequence diagrams.
So I close this PR, which was only meant for the discussion about the right level of abstraction.

**Pull request closed without merging**
