### PR TITLE
Add hono user to docker images

### PR DESCRIPTION
**Pull request by michaelkrebs94**
This adds a user `hono` to the docker images of services and adapters, and uses it to run the application.
This provides additional security, because currently all applications run as root.

### CODE REVIEW

**Comment by sophokles73** [comment]
@michaelkrebs94 The integration tests do not seem to work with your changes. Would you mind taking a look?
Is there a particular reason why you want to specify the UID when creating the hono user? I also wonder if we could/should add the `--no-create-home` switch as we do not need a home directory for the user ...

**Comment by michaelkrebs94** [comment]
@sophokles73 I am looking into the integration tests.
The UID is specified in order to use it in a [Kubernetes SecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), which requires specifying the UID instead of the username.

**Comment by sophokles73** [comment]
My understanding is that if you configure the kubernetes security context, then kubernetes makes sure to run the container using the configured UID, GID (instead of the root user). In this case, you do not need to specify a particular UID, GID at all in the Dockerfile when building the image, or am I mistaken?

**Comment by michaelkrebs94** [comment]
@sophokles73 you are right, the kubernetes securityContext does not need the UID to exist in the container.
Would you recommend creating the user anyway, or can we close this PR?

**Comment by sophokles73** [comment]
FMPOV we can close it ...

**Pull request closed without merging**
