### PR TITLE
Add a spec version in the API management URLs

### PR DESCRIPTION
**Pull request by jbtrystram**
As suggested in https://github.com/eclipse/hono/issues/1366

Signed-off-by: Jean-Baptiste Trystram <jbtrystram@redhat.com>

### CODE REVIEW

**Comment by sophokles73** [comment]
@jbtrystram can you please start your commit messages with the issue that the commit addresses, e.g.
```
[#1366] Add version specifier to endpoint name.
```

In the commit message you may also add
```
Fixes #1366 
```
in order to automatically close the corresponding issue the PR gets merged ...

**Comment by jbtrystram** [comment]
@dejanb the swagger UI already have this information. appart from the getting started guide, what are the other places I need to update ?

**Comment by dejanb** [comment]
@jbtrystram Yeah, I meant on "getting started guide". We don't/can't fix it in this pr, just wanted to make sure we don't forget it.

**Comment by sophokles73** [comment]
@dejanb @jbtrystram I think this can be done as part of #1371 which we can only merge when creating 1.0-M6 anyways ...

**Pull request merged**
