### PR TITLE
isValidUri should not be serialized in device registry

### PR DESCRIPTION
**Pull request by BobClaerhout**
Signed-off-by: Bob Claerhout <claerhout.bob@gmail.com>

### CODE REVIEW

**Comment by BobClaerhout** [comment]
@sophokles73 this bug is present in 1.7.0 release. Any chance this might be added to a 1.7.1 release somehow? If so, do you have any idea when this 1.7.1 release might happen?

**Comment by sophokles73** [comment]
@BobClaerhout We can surely add this to 1.7.1. We usually do a service release if there is  a severe bug to be fixed and/or if a reasonable amount of issues have been fixed. In general, we can do a service release whenever we want. That said, we already have four issues in https://github.com/eclipse/hono/projects/53 so we could do the release as soon as these are fixed ...

**Review by sophokles73 — APPROVED** [review]
LGTM

**Comment by BobClaerhout** [comment]
@sophokles73, ok. thanks for explanation. Created the PR: https://github.com/eclipse/hono/pull/2613

**Pull request merged**
