### PR TITLE
#1486 Improve usability of CLI

### PR DESCRIPTION
**Pull request by johnMinelli**
I tried to follow the suggestions detailed in the issue, to let the CLI be more attractive and self explanatory. I also tried to maintain for back-compatibility the spring configuration at startup. Executing the client with all parameters as in the guide those become the default (so you don't need to specify every time them when executing commands) otherwise the parameters in the application.yml were read and stored as default.

Signed-off-by: Giovanni Minelli <giovanni.minelli3@gmail.com>

### CODE REVIEW

**Comment by calohmn** [comment]
@johnMinelli Can you squash the commits into one commit that contains the "signed-off-by" footer? Then the ECA check should succeed.

**Comment by johnMinelli** [comment]
sorry ahah i'm making a mess, i'll try

**Comment by kaniyan** [comment]
@johnMinelli What I see from the last commits is that the ECA (Eclipse Contributor Agreement) validation fails. Did you already sign the ECA? It is required for contributing to Hono. For more information, please check the below resources.

- https://github.com/eclipse/hono/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement
- https://www.eclipse.org/legal/ECA.php

If you have already signed the ECA, then ensure that you use the same email id to sign-off commits.

**Comment by johnMinelli** [comment]
yes i've signed the ECA as 'Giovanni Minelli' but with Intellij the auto signin was as 'johnMinelli'. However if i understood i need to make a single commit with all my changes signed.
So a rebase to master's sources and then a single commit? or do i make another fork?

**Comment by kaniyan** [comment]
> 
> 
> yes i've signed the ECA as 'Giovanni Minelli' but with Intellij the auto signin was as 'johnMinelli'. However if i understood i need to make a single commit with all my changes signed.
> So a rebase to master's sources and then a single commit? or do i make another fork?

The last commit shows `Signed-off-by: Giovanni Minelli <giovanni.minelli3@gmail.com>`. 
Did you sign the ECA agreement using this email address `giovanni.minelli3@gmail.com`. You can also check by clicking the red x sign next to your commit in this PR. If you didn't use the same email id, then create a new commit and sign-off with the correct email id.  Squash your commits into a singe one, rebase with master and then you can force push to your branch `johnMinelli:#1486_CLI`.

**Comment by johnMinelli** [comment]
Sorry but i think i've made a mess with my fork... i'll try to start from 0 with a new one. Be patient :)

**Pull request closed without merging**
