### PR TITLE
[#3115] Remove Spring Boot based HTTP adapter

### LINKED ISSUE #3115: Remove Spring Boot based HTTP adapter

### PR DESCRIPTION
**Pull request by sophokles73**
Fixes #3115

### CODE REVIEW

**Comment by calohmn** [comment]
Removing the postman collection here was deliberate, right? I guess the collection there was anyway rather invisible, it also not being mentioned anywhere.

**Comment by sophokles73** [comment]
@calohmn The fact that I wasn't even aware of the collection seems to support your assumption ;-)

**Comment by calohmn** [comment]
yes, I wasn't aware of it either.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
