### PR TITLE
Upgrade to Quarkus 2.8.3

### LINKED ISSUE #3254: Upgrade to latest Quarkus 2.8 service release

### PR DESCRIPTION
**Pull request by sophokles73**
Fixes #3254

### CODE REVIEW

**Comment by calohmn** [comment]
@sophokles73 What about Quarkus 2.9.0? Any obstacles in upgrading to that version already?

**Comment by sophokles73** [comment]
Well, that close to the 2.0.0 release I did not want to upgrade to the initial new minor version, hoping that the third service release version of the existing 2.8 version would provide for more stability. Is there something in 2.9.0 that you believe would be very helpful/beneficial?

**Comment by calohmn** [comment]
> Is there something in 2.9.0 that you believe would be very helpful/beneficial?

No, not really, so I'm fine with using 2.8.3.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
