### PR TITLE
Define revision in parent pom

### PR DESCRIPTION
**Pull request by pho-enix**
* Make it possible to override version via mvn property
* Reduce changes introduced by release

Signed-off-by: Sebastian Poehn <sebastian.poehn@bosch-si.com>

### CODE REVIEW

**Comment by pho-enix** [comment]
I understand that you have the version update well automated for the Hono project.

The motivation for this PR comes from a vendoring perspective. We maintain a fork of Hono with some custom adoptions. We have our own schema for build numbers which we want to set externally and not in the pom.xml. With this change, we can simply `-Drevision=2018-05-08-41pre`.

**Comment by sophokles73** [comment]
> With this change, we can simply -Drevision=2018-05-08-41pre

in order to do what exactly?

**Comment by pho-enix** [comment]
Let's say I want Hono jars with a `2018-05-08-41pre` versioning.
I want subsequent build numbers because of security patches.

**Comment by pho-enix** [comment]
Maybe you can elaborate how hono project updates the versions of the packages.

If this is some neat functionality I will be happily using this for my very purpose.

**Comment by sophokles73** [comment]
In order to set a new version:
mvn versions:set -DnewVersion=1.0-MY_VERSION

reverting the changes:
mvn versions:revert

**Comment by pho-enix** [comment]
Tried it out. Works perfectly for us :)

Thanks a lot for the support.

**Pull request closed without merging**
