### PR TITLE
Add lora adapter to deploy

### PR DESCRIPTION
**Pull request by BobClaerhout**
Requires https://github.com/eclipse/hono/pull/1479 to be merged.

### CODE REVIEW

**Comment by BobClaerhout** [comment]
Can somebody trigger the travis build again? It seems to be a maven central issue

**Comment by calohmn** [comment]
@BobClaerhout travis build is green now. There are some conflicts now however, can you have a look?

**Comment by sophokles73** [comment]
@BobClaerhout Thanks for submitting these improvements to the LoRa adapter :+1: 

I would like to split up this rather big PR into several, easier to handle, parts. Can we maybe start with adding the banner, log config, key and cert in an initial step? After that we can deal with integrating the adapter into the Helm chart, ok?

**Comment by BobClaerhout** [comment]
@sophokles73, first PR is created: https://github.com/eclipse/hono/pull/1501

**Comment by BobClaerhout** [comment]
@sophokles73 , second PR also created: https://github.com/eclipse/hono/pull/1502
We can close this PR now

**Pull request closed without merging**
