### PR TITLE
Add information on accepted date/time format in the device registry management API

### PR DESCRIPTION
**Pull request by kaniyan**

### CODE REVIEW

**Review by sophokles73 — COMMENTED** [review]
actually it needs to be a string that complies with the format defined in [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) as indicated by the `date-time` format used for the properties (see http://spec.openapis.org/oas/v3.0.3#dataTypeFormat) ...

**Comment by kaniyan** [comment]
> actually it needs to be a string that complies with the format defined in [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) as indicated by the `date-time` format used for the properties (see http://spec.openapis.org/oas/v3.0.3#dataTypeFormat) ...

I am not aware that this has been already indicated by the `date-time` format in the OpenAPI spec. Since it is already defined in OpenAPI spec, there is no need to define again and this PR can be closed. WDYT?

**Comment by sophokles73** [comment]
> Since it is already defined in OpenAPI spec, there is no need to define again and this PR can be closed. WDYT?

In general, I agree and that is what I had hoped readers would determine as well. However, it might not be a bad idea to make this more explicit as we have seen in #2376 ...

**Comment by kaniyan** [comment]
@sophokles73 I have updated accordingly and pushed those changes. Would you mind taking an another look?

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
