### PR TITLE
[#1593] Creating HttpAdapterMetrics bean for sigfox and lora

### LINKED ISSUE #1593: Add metrics to Lora and Sigfox adapters
The Lora and Sigfox adapters should also report the metrics that Hono's other adapters support.

### PR DESCRIPTION
**Pull request by thiyagu-7**
Creating the bean for `MicrometerBasedHttpAdapterMetrics` for Lora and Sigfox

Closes #1593

### CODE REVIEW

**Comment by sophokles73** [comment]
Can you also update the Metrics API documentation under `site/documentation/api` accordingly?

**Comment by thiyagu-7** [comment]
If I understand right, I need to add Lora and Sigfox component names to
https://github.com/eclipse/hono/blob/2103f4722166cd19614c6d98db4f1922416ebebd/site/documentation/content/api/Metrics.md

Am I right?

**Comment by sophokles73** [comment]
@thiyagu-7 can you please also add yourself to the *Copyright Holders* section of the `legal/src/main/resources/legal/NOTICE.md` file?

**Comment by thiyagu-7** [comment]
> @thiyagu-7 can you please also add yourself to the _Copyright Holders_ section of the `legal/src/main/resources/legal/NOTICE.md` file?

Done. I've added it to the previous commit itself.

**Pull request merged**
