### PR TITLE
[#1381] COAP adapter reports metrics based on minimum message size

### PR DESCRIPTION
**Pull request by kaniyan**
This PR is implementation for #1381.

### CODE REVIEW

**Comment by kaniyan** [comment]
> Looks good but can you please also document the removal of the method in the release notes?

sure. As I remember,  the next planned release is 1.0? If so, I can document it under _1.0 (not yet released)_.

**Comment by sophokles73** [comment]
let's not get too cocky ... 1.0-M7

**Comment by kaniyan** [comment]
> let's not get too cocky ... 1.0-M7

After the 1.0-M6 release, the current version has been bumped to _1.0.0-SNAPSHOT_. Also a reason to think it could be 1.0.0 :wink:. I will update the release notes for 1.0-M7.

**Comment by kaniyan** [comment]
@sophokles73 Information about removal of the methods is now available in the release notes.

**Pull request merged**
